MyThreadPool
YuriUfimtsev/SPbU-CSharp-course pull request #3
Opened 2022-10-26 19:07 UTC by YuriUfimtsev

2022-12-26 13:58 UTC, yurii-litvinov requested changes
Вообще, сделано основательно и довольно годно, но есть пара важных косяков именно в плане многопоточности

2022-12-26 13:58 UTC, yurii-litvinov commented on Homework3/MyThreadPool/IMyTask{TResult}.cs
> +using System.Text;
Думаю, что что-то из этого не нужно

2022-12-26 13:58 UTC, yurii-litvinov commented on Homework3/MyThreadPool/MyTask{TResult}.cs
> +public class MyTask<TResult> : IMyTask<TResult>
Этот класс лучше сделать private-вложенным в тредпул, чтобы у внешнего кода не было соблазна вызвать Compute или что-то такое.

2022-12-26 13:58 UTC, yurii-litvinov commented on Homework3/MyThreadPool/MyTask{TResult}.cs
> +        return this.myThreadPool.Submit(() => func(this.Result), this.continuationResetEvent);
Нет, так нельзя — если исходная задача длинная, то continuation-ы будут сидеть в пуле и ждать parentalContinuationResetEvent, занимая потоки. Так что если, скажем в пуле 10 потоков, мы добавляем задачу, которую считать два часа и 9 Continuation-ов к ней, а потом ещё 9 коротких задач, эти короткие задачи смогут начать считаться только через два часа. В правильном решении Continuation-ы ставятся на пул только по окончании исходной задачи, так что другие задачи могут спокойно пользоваться потоками пула, пока исходная задача считается.

2022-12-26 13:58 UTC, yurii-litvinov commented on Homework3/MyThreadPool/MyTask{TResult}.cs
> +    private ManualResetEvent continuationResetEvent;
Это сложно и незачем, потому что в ContinueWith мы бы всё равно блокировались на Result

2022-12-26 13:58 UTC, yurii-litvinov commented on Homework3/MyThreadPool/MyThreadPool.cs
> +    private ManualResetEvent manualResetEvent;
Не очень говорящие названия

2022-12-26 13:58 UTC, yurii-litvinov commented on Homework3/MyThreadPool/MyThreadPool.cs
> +    }
```suggestion
    public bool AreAllTasksInProgress => this.tasksQueue.Count == 0;
```

2022-12-26 13:58 UTC, yurii-litvinov commented on Homework3/MyThreadPool/MyThreadPool.cs
> +        var myTask = parentalTaskResetEvent == null ? new MyTask<TResult>(function, this)
cancellationTokenSource не проверяется... Вызывающий может получить задачу, которую уже точно никто не будет считать.

2022-12-26 13:58 UTC, yurii-litvinov commented on Homework3/MyThreadPool/MyThreadPool.cs
> +                WaitHandle.WaitAny(this.myThreadPool.resetEventsArray);
Вот это, кстати, хорошая идея, позволяет легко сделать остановку всех тредов сразу

2022-12-26 13:58 UTC, yurii-litvinov commented on Homework3/MyThreadPool/MyThreadPool.cs
> +                    this.myThreadPool.manualResetEvent.Reset();
А если как раз в этот момент Submit вкинет новую задачу, будет дедлок

2022-12-26 13:58 UTC, yurii-litvinov commented on Homework3/MyThreadPool/MyThreadPool.cs
> +        this.autoResetEvent.Set();
autoResetEvent разбудит один поток. Так что, скажем, если у нас было 10 потоков в тредпуле, мы 10 раз вызвали Submit до переключения потоков, разбудится один поток, остальные задачи будут ждать

2022-12-26 13:58 UTC, yurii-litvinov commented on Homework3/MyThreadPoolTests/MyThreadPoolTests.cs
> +}
Надо ещё тесты на конкурентнный доступ к методам пула, типа Submit и Shutdown одновременно

2022-12-27 11:28 UTC, YuriUfimtsev commented on Homework3/MyThreadPool/MyTask{TResult}.cs
> +    private ManualResetEvent continuationResetEvent;
В противном случае мы в Compute можем вернуть null как текущее значение "private TResult? result;" родительской задачи

2022-12-27 12:29 UTC, YuriUfimtsev commented on Homework3/MyThreadPool/MyThreadPool.cs
> +        this.autoResetEvent.Set();
Разбудится, выполнит задачу, и разбудит остальные. Можно еще добавить проверку на количество задач в очереди перед выполнением задачи

2023-02-03 14:58 UTC, merged